### ISSUE TITLE
Welcome Tad Dallas!

### ISSUE THREAD

**Issue by opetchey** [opetchey/RREEBES#105]
http://taddallas.github.io

Try to have a time for him to introduce himself in person.

**Comment by taddallas** [comment]
Hey all, 
I'm Tad, a PhD student at University of Georgia. I have half-contributed the reproduction of one of the papers ([Yampolsky et al. 2014](https://github.com/opetchey/RREEBES/tree/master/Yampolsky2014)). I will likely continue working on it, and see if I can't get the whole thing working (currently a couple of the tables are off). I'm happy to back off and let somebody else take a crack at it though too. I don't want to hog the fun.
Cheers,
Tad

**Comment by opetchey** [comment]
Welcome from our first meeting. Do let us know if you can make one in person, i.e., by Skype.
