### ISSUE TITLE
Permission for updating minutes

### ISSUE THREAD

**Issue by davidinauen** [opetchey/RREEBES#115]
@opetchey Hi Owen. I tried to update the minutes for last week (together with Frank), but it seems I'm not eligible to push my new version of it. Do you mind giving me the appropriate permission to update them? cheers

**Comment by opetchey** [comment]
Hi David.
Can you please instead fork the repository, make your changes and commit them to your fork, then submit a pull request to my repo?
(Come by if you need a hand.)
Owen
