### ISSUE TITLE
Beninca: Not all variables/spp groups were detrended

### ISSUE THREAD

**Issue by dennismhansen** [opetchey/RREEBES#42]
Vanessa's eagle eyes spotted a potential reason for why Frank & Jason's plots looked different: Carefully reading the supplementary info, it says that "Most species did not show long-term trends, except for the bacteria, detritivores (ostracods and harpacticoid copepods), dissolved inorganic nitrogen and soluble reactive phosphorus"  - and that's it. 
Checking the code Owen received from Ellner, it seems that they actually only detrended the ones that DID show long-term trends (excerpt):
# create the data series

Cyclopoids=X$Cyclopoids^0.25; 
Protozoa=X$Protozoans^0.25; 
Rotifers=X$Brachionus^0.25; 
Calanoids=X$Eurytemora^0.25;  
Pico=X$Picophytopl^0.25;
Nano=X$Green.Flagellates^0.25; 
Net=X$Melosira^0.25;  
Nitrogen=Detrend(X$TotalN^0.25);
PO4=Detrend(X$PO4^0.25); 
Bacteria=Detrend(X$Bacteria^0.25); 
Ostracods=Detrend(X$Ostracods^0.25); 
Harpacticoids=Detrend(X$Harpacticoids^0.25);

**Comment by opetchey** [comment]
Owen has implemented this in the Owen_boost branch

**Comment by thomassie** [comment]
How does one know whether there is a long-term trend or not?

**Comment by opetchey** [comment]
Visual inspection, in this paper...
