### ISSUE TITLE
cannot commit

### ISSUE THREAD

**Issue by marcoplebani85** [opetchey/RREEBES#7]
Hi Owen! I installed GitHub on my mac, cloned the RREEBES repository on my desktop and made some changes (changed a file and created a new text file) and commit them. But when it comes to sync the commits to Git, I get: "Authentication Failed. You may not have permission to access RREEBES. Check Preferences to make sure you’re still logged in." Any ideas? Do you need to authorize me as a contributor? I'll look more into this, else we can fix this on next meeting. 
Cheers,
M

**Comment by opetchey** [comment]
Try forking the repository first, then clone from your github account.
