### ISSUE TITLE
Updating forked repo

### ISSUE THREAD

**Issue by pennekampster** [opetchey/RREEBES#9]
Dear all, no need to become collaborator. You can update the forked repo/local copy by adding the mother repo (https://github.com/opetchey/RREEBES.git) as another remote to your forked repository. You can then pull directly updates from the mother repo, make local changes, push back to the forked repo and send a pull request to Owen!

**Comment by opetchey** [comment]
Please put this in the wiki!

**Comment by pennekampster** [comment]
Done!
